import type { Metadata } from "next";
import "./globals.css";
import Providers from "./providers";
import { merienda } from "./fonts";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={merienda.className}>
        <Providers>
          {children}
        </Providers>
      </body>
    </html>
  );
}
